site_name: Animaquina
site_url: https://www.animaquina.com
theme:
  name: material
  logo: assets/logo.png
  palette:
    scheme: slate
    primary: black
    accent: deep orange
extra_css:
  - stylesheets/extra.css